### ISSUE TITLE
Remove Sidebar

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/muff#11]
I think something got lost in translation from mockups to code. There should not be a sidebar UI going on, as it's extra UI that doesn't do anything.

The idea with the window contents layout is to mimic the Gtk+ dialog style, as seen here:

![image](https://user-images.githubusercontent.com/611168/37424210-92fc9120-2785-11e8-9f95-ca0d19605fc7.png)

```shell
zenity --info --text="<b>Here is some text</b>\n\nThis is fairly standard Gtk+ dialog style."
```

**Comment by WatchMkr** [comment]
I agree. Let's pull back a bit to the simpler look. It matches better with existing applications.
