### ISSUE TITLE
GTK3 Progress

### ISSUE THREAD

**Issue by mmstick** [pop-os/muff#5]
I might could pull it off in a short time frame, if you'd like to have a GTK3 interface, in addition to the CLI.

**Comment by jackpot51** [comment]
Yeah, that would be great!

**Comment by mmstick** [comment]
Alright, I'll send over a PR soon which splits the project up into a library, a CLI binary, and a GTK binary. The GTK binary will be a dummy at first, though, but I'll immediately begin working on the GTK interface after submitting the PR.

**Comment by mmstick** [comment]
Didn't get to spend much time on it today, but this is what I've got thus far:

![screenshot from 2018-03-04 22-51-22](https://user-images.githubusercontent.com/4143535/36956975-3dbc9c1a-1fff-11e8-9f77-e3b433745c93.png)

**Comment by WatchMkr** [comment]
Nice start! Let's give it a GNOME 3 feel similar to the screenshot utility. (My symbolic images are awful but I'm sure we can find better ones).

![usb-flasher-mockup](https://user-images.githubusercontent.com/3430283/36978681-61693e78-2042-11e8-869f-96498393060b.png)

**Comment by WatchMkr** [comment]
Thinking through this a bit more, changing the button to the file name/drives is a bad idea. We can try adding the image name and drives under the button once they're selected that way the user can press the button again to change the image or drives.

**Comment by mmstick** [comment]
@WatchMkr Thanks! I'll look into this later today. Only got to spend about an hour on the GTK binary yesterday.

**Comment by jackpot51** [comment]
![img_20180305_094301](https://user-images.githubusercontent.com/7741236/36987684-2f338f18-205a-11e8-9d8b-7d981b715c05.jpg)

**Comment by jackpot51** [comment]
That is @cassidyjames quick suggestion. Symbolic icons and default color scheme as @WatchMkr suggested, and I think we are all on the same page

**Comment by WatchMkr** [comment]
Why are we not using GNOME 3 header bar? This does not match the design of other GNOME apps.

**Comment by cassidyjames** [comment]
My sketch was super simple and not supposed to be taken pixel-by-pixel. :P We could easily add a headerbar, and having the Flash button in the headebar might work. My only concern with that is that this is a closable window, so the close button goes in the far-right headerbar position, and an affirmative Flash button might look awkward there.

I think the screenshot tool is a parentless dialog, which is explicitly discouraged in the toolkit. Initial Setup is not closable, so it doesn't have the problem of the affirmative button and the close button fighting for space.

**Comment by cassidyjames** [comment]
Spec being hashed out per @WatchMkr's request at https://github.com/pop-os/muff/wiki/GUI-Design

**Comment by mmstick** [comment]
@cassidyjames Tell me when you're finished with the spec, and I'll quickly implement everything w/ `gtk-rs`

**Comment by cassidyjames** [comment]
@mmstick first two screens have been more specced out. Working on the last two.

**Comment by cassidyjames** [comment]
@mmstick alright, I think it's ready for you. Hit me up if you have any questions.

**Comment by mmstick** [comment]
I'll start on it soon, once I finish up with the distinst-related stuff I'm working on at the moment.

**Comment by mmstick** [comment]
Made some initial progress. Moving forward will set the animation to right to left, and moving backward will move from left to right. The next button is set to sensitive after an .iso or .img is selected (which are filtered in a file chooser dialog). Not currently displaying the ISO path after it is selected, or setting the hash yet. The devices screen also isn't implemented beyond the image and description.

![01](https://user-images.githubusercontent.com/4143535/37012066-c4fd6a94-20c0-11e8-914b-00157df70c5d.png)
![02](https://user-images.githubusercontent.com/4143535/37012067-c50e0eb2-20c0-11e8-8628-2ac583e1dc58.png)


Source code is available [here](https://github.com/mmstick/muff/tree/gtk/gtk).

**Comment by jackpot51** [comment]
Looks good!

**Comment by mmstick** [comment]
Made a little more progress. Hashes for MD5 & Sha256 are working.

![screenshot from 2018-03-06 01-00-13](https://user-images.githubusercontent.com/4143535/37016481-66f38806-20da-11e8-8186-106aabc03eab.png)

**Comment by jackpot51** [comment]
I am not sure the generate button is necessary, if it can regenerate when the selection is changed

**Comment by cassidyjames** [comment]
I might learn how to use GTK in Rust and poke at some margins, but this is looking great!

**Comment by mmstick** [comment]
@cassidyjames This might be helpful. I was working on it shortly before getting hired: https://mmstick.github.io/gtkrs-tutorials/

**Comment by cassidyjames** [comment]
We discussed the hash a bit, and I did some thinking about how to avoid the performance hit of calculating unless the user explicitly wants to, without adding too much crazy UI. Here's what I came to:

![img_20180306_150848](https://user-images.githubusercontent.com/611168/37061358-7d15bb74-2150-11e8-9e05-825965764ffa.jpg)

This would be a grid with a right-aligned `Hash:` label, then a dropdown button linked to an entry (I think this is supported in GTK and our stylesheet, if not, let me know). 

The dropdown label would be `Type` by default, and the menu would have all the accepted types in it. Selecting a type should change the dropdown label to match the type and begin calculating a hash. 

While calculating, we should pack a spinner in the entry's primary icon location. The entry should be non-editable, monospace, and have a width request of the maximum length a hash would be (that way it's predictable and shouldn't resize the window when the has loads.

Let me know if that doesn't make sense or work out. I'll also add this to the wiki.

**Comment by mmstick** [comment]
Device selection & flashing works, but the progress & summary views aren't fully implemented yet.

![screenshot from 2018-03-07 01-24-08](https://user-images.githubusercontent.com/4143535/37076993-e3336d06-21a6-11e8-9373-97b67f294804.png)

The devices are populated once that view is opened, but it doesn't yet perform any live updates to update the list, so it will only update if you go back and click next again.

Changes were also made to the image selection view, which now preloads the ISO in RAM in advance, and only calculates a hash (using the in-memory copy of the ISO) when a hash is selected. Haven't yet added the spinner though.

![04](https://user-images.githubusercontent.com/4143535/37077084-5ce7c6f6-21a7-11e8-9091-706e66ec8397.png)

**Comment by mmstick** [comment]
Spent a little time on this today, and was able to get the multiple progress bars working in the progress view, as can be seen. One of the three flash drives is USB 2.0, while the other two are USB 3.0. It's easy to tell which one is USB 2.0.

![progress](https://user-images.githubusercontent.com/4143535/37248510-336cd46c-24a2-11e8-96d4-63506fde6dd9.png)

**Comment by mmstick** [comment]
Spent some time refactoring the code base, and then improved the styling in the progress view. Also added labels to show the rate of each device being flashed.

![progress2](https://user-images.githubusercontent.com/4143535/37250780-2e3ebc7a-24da-11e8-9bb0-bbb7af501b41.png)

**Comment by mmstick** [comment]
Here's a GIF of the program in action, as it is now.

![muff](https://user-images.githubusercontent.com/4143535/37262066-28570ff4-2577-11e8-81a4-f00c0bb0255b.gif)

**Comment by mmstick** [comment]
There's now a .desktop and .policy file that gets installed, and it's possible to set the GTK app as the default application for opening ISOs. The write rate label has also been improved.


![peek 2018-03-13 15-28](https://user-images.githubusercontent.com/4143535/37365241-4ab9ab9e-26d3-11e8-807a-4b9a3b682d8f.gif)

**Comment by jackpot51** [comment]
That is looking good @mmstick , it is time to merge.

**Comment by jackpot51** [comment]
I have merged it. Future GTK3 items will be handled in separate issues, on the master branch.

**Comment by mmstick** [comment]
@jackpot51 Thanks!
